export enum DispatchEventType {
  ASSIGNMENT_OFFERED = 'ASSIGNMENT_OFFERED',
  ASSIGNMENT_CONFIRMED = 'ASSIGNMENT_CONFIRMED',
  ASSIGNMENT_TIMEOUT = 'ASSIGNMENT_TIMEOUT',
  ASSIGNMENT_COMPLETED = 'ASSIGNMENT_COMPLETED',
  ASSIGNMENT_CANCELLED = 'ASSIGNMENT_CANCELLED',
}

export enum DriverEventType {
  ASSIGNMENT_ACCEPTED = 'ASSIGNMENT_ACCEPTED',
  ASSIGNMENT_REJECTED = 'ASSIGNMENT_REJECTED',
  ORDER_COMPLETED = 'ORDER_COMPLETED',
  ORDER_CANCELLED = 'ORDER_CANCELLED',
}
