export enum DispatchOrderEventType {
  ASSIGNMENT_OFFERED = 'ASSIGNMENT_OFFERED',
  ASSIGNMENT_CONFIRMED = 'ASSIGNMENT_CONFIRMED',
  ASSIGNMENT_COMPLETED = 'ASSIGNMENT_COMPLETED',
  ASSIGNMENT_CANCELLED = 'ASSIGNMENT_CANCELLED',
}
