export enum DriverEventType {
  STATUS_CHANGED = 'DRIVER_STATUS_CHANGED',
  ASSIGNMENT_OFFERED = 'ASSIGNMENT_OFFERED',
  ASSIGNMENT_ACCEPTED = 'ASSIGNMENT_ACCEPTED',
  ASSIGNMENT_REJECTED = 'ASSIGNMENT_REJECTED',
  ASSIGNMENT_TIMEOUT = 'ASSIGNMENT_TIMEOUT',
  ORDER_COMPLETED = 'ORDER_COMPLETED',
  ORDER_CANCELLED = 'ORDER_CANCELLED',
}
